CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL IDENTITY, 
    [BASLIK] NCHAR(50) NULL, 
    [ALTBASLIK] NCHAR(50) NULL, 
    [ACIKLAMA] NCHAR(250) NULL, 
    [GNOT] NCHAR(10) NULL, 
    [TARİH] NCHAR(50) NULL
)
