CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL IDENTITY , 
    [AD] NCHAR(20) NULL, 
    [SOYAD] NCHAR(20) NULL, 
    [ADRES] NCHAR(150) NULL, 
    [MAIL] NCHAR(100) NULL, 
    [TELEFON] NCHAR(20) NULL, 
    [KISANOT] NCHAR(1000) NULL
)
